version: '3.4'

x-common:
  &common
  image: apache/airflow:2.5.0
  user: "${AIRFLOW_UID}:0"
  env_file:
    - .env
  volumes:
    - ./app/dags:/opt/airflow/dags
    - ./app/logs:/opt/airflow/logs

x-depends-on:
  &depends-on
  depends_on:
    postgres:
      condition: service_healthy
    airflow-init:
      condition: service_completed_successfully

services:
  #Metabase service
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: airflow
      MB_DB_PORT: 5432
      MB_DB_USER: airflow
      MB_DB_PASS: airflow
      MB_DB_HOST: postgres
    depends_on:
      - postgres  #after PostgreSQL
  minio:
    image: minio/minio:latest
    ports:
      - '9000:9000'
      - '9090:9090'
    volumes:
      - './minio_data:/data'
    env_file:
      - .env
    command: server --console-address ":9090" /data

  dw_postgres:
    image: postgres:13
    container_name: dw_postgres
    ports:
      - "5434:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "dw" ]
      interval: 5s
      retries: 5
    env_file:
      - .env.dw_postgres
    volumes:
      - ./sql:/docker-entrypoint-initdb.d

  postgres:
    image: postgres:13
    container_name: postgres
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "airflow" ]
      interval: 5s
      retries: 5
    env_file:
      - .env

  scheduler:
    image: apache/airflow:2.5.0
    user: "${AIRFLOW_UID}:0"
    env_file:
      - .env
    volumes:
      - ./app/dags:/opt/airflow/dags
      - ./app/logs:/opt/airflow/logs
      - ./app/config:/opt/airflow/config  #profiles.yml is in ./app/config
    container_name: airflow-scheduler
    command: scheduler
    restart: on-failure
    ports:
      - "8793:8793"
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully

  webserver:
    image: apache/airflow:2.5.0
    user: "${AIRFLOW_UID}:0"
    env_file:
      - .env
    volumes:
      - ./app/dags:/opt/airflow/dags
      - ./app/logs:/opt/airflow/logs
      - ./app/config:/opt/airflow/config  #profiles.yml is in ./app/config
    container_name: airflow-webserver
    restart: always
    command: webserver
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 30s
      retries: 5

  airflow-init:
    image: apache/airflow:2.5.0
    user: "${AIRFLOW_UID}:0"
    env_file:
      - .env
    volumes:
      - ./app/dags:/opt/airflow/dags
      - ./app/logs:/opt/airflow/logs
      - ./app/config:/opt/airflow/config  #profiles.yml is in ./app/config
    container_name: airflow-init
    entrypoint: /bin/bash
    command:
      - -c
      - |
        mkdir -p /sources/logs /sources/dags
        chown -R "${AIRFLOW_UID}:0" /sources/{logs,dags}
        exec /entrypoint airflow version